env:
  browser: false
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-constant-condition: off
  no-mixed-spaces-and-tabs: off
  no-unused-expressions: off
  no-unused-vars: off
  no-useless-escape: off
globals:
  Buffer: readonly
  Intl: readonly
  afterEach: readonly
  beforeAll: readonly
  beforeEach: readonly
  clearInterval: readonly
  console: readonly
  describe: readonly
  expect: readonly
  inject: readonly
  it: readonly
  jasmine: readonly
  module: readonly
  pending: readonly
  process: readonly
  require: readonly
  setImmediate: readonly
  setInterval: readonly
  setTimeout: readonly
  spyOn: readonly
