# -*- mode: docker-compose; -*- vim: set ft=yaml:
version: '3.7'

services:
  web:
    build: .
    depends_on:
      - postgis
    image: fdean/trip-server
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        #max_attempts: 3
        window: 90s
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 30M
    ports:
      - 8080:8080
    environment:
      TRIP_SIGNING_KEY_FILE: /run/secrets/jwt_signing_key
      TRIP_RESOURCE_SIGNING_KEY_FILE: /run/secrets/jwt_resource_signing_key
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - jwt_signing_key
      - jwt_resource_signing_key
      - postgres_password

  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    image: fdean/trip-database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 90s
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 20M
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - trip-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

secrets:
  jwt_signing_key:
    external: true
  jwt_resource_signing_key:
    external: true
  postgres_password:
    external: true

volumes:
  trip-db-data:
