# -*- mode: dockerfile; -*- vim: set ft=dockerfile:
FROM postgres:13.9-bullseye
LABEL uk.co.fdsd.tripserver.db.version="1.11.3"
#LABEL uk.co.fdsd.tripserver.db.release-date="2022-12-25"
#LABEL uk.co.fdsd.tripserver.db.is-production=""

ENV POSTGIS_MAJOR 3
ENV POSTGIS_VERSION 3.1.1+dfsg-1
RUN apt-get update \
    && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
    && apt-get install -y --no-install-recommends \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
    postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \
    && rm -rf /var/lib/apt/lists/*
RUN localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8
ENV LANG en_GB.utf8
ENV POSTGRES_USER trip
ENV POSTGRES_DB trip

WORKDIR /docker-entrypoint-initdb.d
RUN mkdir -p /docker-entrypoint-initdb.d
COPY spec/support/10_init-trip-db.sh \
    spec/support/10_trip_role.sql \
    spec/support/20_schema.sql \
    spec/support/30_permissions.sql \
    spec/support/40_path_colors.sql \
    spec/support/50_georef_formats.sql \
    spec/support/60_waypoint_symbols.sql \
    spec/support/90_test-data.sql \
    ./
RUN gzip *.sql
