# -*- mode: docker-compose; -*- vim: set ft=yaml:
version: '3.7'

services:
  web:
    build: .
    depends_on:
      - postgis
    image: fdean/trip-server:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 90s
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
        reservations:
          cpus: '0.25'
          memory: 40M
    ports:
      - 8080:8080
    environment:
      TRIP_SIGNING_KEY: divmyelfajsa
      TRIP_RESOURCE_SIGNING_KEY: niqueSlothUg
      POSTGRES_PASSWORD: EgceOvovbiag
      CONFIGURE_TILE_SERVER: 'yes'

  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgis
      shm_size: 256m
    image: fdean/trip-database:latest
    shm_size: 512m
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 90s
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
        reservations:
          cpus: '0.1'
          memory: 20M
    volumes:
      - trip-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: EgceOvovbiag
  map:
    image: overv/openstreetmap-tile-server:v1.8.0
    shm_size: 192m
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 90s
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 400M
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
      - "8081:80"
    command: "run"

volumes:
  trip-db-data:
  openstreetmap-data:
  openstreetmap-rendered-tiles:
