# -*- mode: docker-compose; -*- vim: set ft=yaml:
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      TRIP_SIGNING_KEY: divmyelfajsa
      TRIP_RESOURCE_SIGNING_KEY: niqueSlothUg
      POSTGRES_PASSWORD: EgceOvovbiag
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ../trip-web-client/app:/app/app
      - web_node_modules:/app/app/node_modules
    command: ./node_modules/nodemon/bin/nodemon.js --ignore app/ index.js

  postgis:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    volumes:
      - trip-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: EgceOvovbiag

volumes:
  trip-db-data:
  trip-web-client:
  web_node_modules:
  node_modules:
